before_install:
- sudo apt-get update -q
- sudo apt-get install -qq apt-transport-https
- curl https://packagecloud.io/varnishcache/varnish41/gpgkey | sudo apt-key add -
- echo "deb https://packagecloud.io/varnishcache/varnish41/ubuntu/ precise main" | sudo tee /etc/apt/sources.list.d/varnish-cache.list
- sudo apt-get -q update
- sudo apt-get install varnish

script:
- make check

